spring:
  application:
    name: SocialMedia
#DATA
  datasource:
    url: jdbc:postgresql://localhost:5432/SocialMedia
    username: postgres
    password: root
#FILE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#SERVER
server:
  port: 8081
#VARIABLES
socialmedia:
  pictures:
    dir: C:/pictures/ #Directory of saved pictures
  security:
    secret: FA0YBcVmpr9CdM3SqfIdqftRjPeuLlL6W/7IcPMvVMc #256-bit secret
    lifetime: 21600000 #Token lifetime
