CREATE Table users(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL,
    date_of_birth DATE NOT NULL,
    profile_picture TEXT,
    country TEXT,
    is_valid BOOLEAN,
    is_private BOOLEAN,
    is_admin BOOLEAN,
    is_blocked BOOLEAN
);

Create TABLE posts(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    photo_url TEXT,
    text TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE Table refresh_tokens(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token TEXT,
    expiry_date DATE,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE Table likes(
    user_id BIGINT NOT NULL,
    post_id BIGINT Not NULL,
    PRIMARY KEY (user_id, post_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (post_id) REFERENCES posts(id)
);

CREATE Table friends(
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (friend_id) REFERENCES users(id)
);

CREATE Table invites(
    user_from BIGINT NOT NULL,
    user_to BIGINT NOT NULL,
    PRIMARY KEY (user_from, user_to),
    FOREIGN KEY (user_from) REFERENCES users(id),
    FOREIGN KEY (user_to) REFERENCES users(id)
);

CREATE Table blacklist(
    user_from BIGINT NOT NULL,
    user_to BIGINT NOT NULL,
    PRIMARY KEY (user_from, user_to),
    FOREIGN KEY (user_from) REFERENCES users(id),
    FOREIGN KEY (user_to) REFERENCES users(id)
);

CREATE TABLE chats(
    id UUID PRIMARY KEY,
    date_of_last_send TIMESTAMP DEFAULT now()
);

CREATE TABLE messages(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_id BIGINT NOT NULL,
    chat_id UUID NOT NULL,
    date_of_send TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    text TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (chat_id) REFERENCES chats(id),
    FOREIGN KEY (sender_id) REFERENCES users(id)
);

CREATE TABLE users_chats(
    user_id BIGINT NOT NULL,
    chat_id uuid NOT NULL ,
    PRIMARY KEY (user_id, chat_id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (chat_id) REFERENCES chats(id)
);
